#!/usr/bin/env bash
sudo apt-get update
python3 -m venv venv
source venv/bin/activate
sudo apt-get install python3-dev -y
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install zlib1g-dev -y
sudo pip3 install mysqlclient -y